<a name="toc_40015_3.2"></a>
## 3.2 NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index. In Course 1, we will represent vectors as NumPy 1-D arrays. 

 - 1-D array, shape (n,): n elements indexed [0] through [n-1]

In [46]:
import numpy as np
import copy
a = np.zeros(5)
print(f'{a} shape:{a.shape} dtype:{a.dtype}')


[0. 0. 0. 0. 0.] shape:(5,) dtype:float64


Some data creation routines do not take a shape tuple:

In [47]:
a = np.arange(4.)
print(f'{a} shape:{a.shape} dtype:{a.dtype}')
a = np.random.rand(4)
print(f'{a} shape:{a.shape} dtype:{a.dtype}')


[0. 1. 2. 3.] shape:(4,) dtype:float64
[0.73722136 0.15910326 0.47623721 0.80409159] shape:(4,) dtype:float64


In [48]:
a = np.arange(10)
try:
    c=a[10]
except Exception as e:
    print(e)

index 10 is out of bounds for axis 0 with size 10



### 3.4.2 Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [49]:
#vector slicing operations
a = np.arange(10)
print(f"a         = {a}")

#access 5 consecutive elements (start:stop:step)
c = a[2:7:1];     print("a[2:7:1] = ", c)

# access 3 elements separated by two 
c = a[2:7:2];     print("a[2:7:2] = ", c)

# access all elements index 3 and above
c = a[3:];        print("a[3:]    = ", c)

# access all elements below index 3
c = a[:3];        print("a[:3]    = ", c)

# access all elements
c = a[:];         print("a[:]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]


In [50]:
a = np.array([1,2,3,4])
print(f"a             : {a}")
# negate elements of a
b = -a 
print(f"b = -a        : {b}")

# sum all elements of a, returns a scalar
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")

b = np.mean(a)
print(f"b = np.mean(a): {b}")

b = a**2
print(f"b = a**2      : {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]


In [51]:
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


In [52]:
#try a mismatched vector operation
c = np.array([1, 2])
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

In [53]:
a = np.array([1, 2, 3, 4])

# multiply a by a scalar
b = 5 * a 
print(f"b = 5 * a : {b}")


b = 5 * a : [ 5 10 15 20]


In [54]:
a = np.zeros((1,5))
print(a)
a = np.arange(6).reshape(-1,2)
print(f'a = {a} a_shape =  {a.shape}')



[[0. 0. 0. 0. 0.]]
a = [[0 1]
 [2 3]
 [4 5]] a_shape =  (3, 2)


### 4.4.2 Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [55]:
a = np.arange(20).reshape(-1,10)
print(a)
print(a[0,2:7:2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[2 4 6]


In [56]:
arr1 = np.array([[1,2,3],[4,5,6]])
print(arr1.sum(axis=1)
,arr1.sum(axis=0))


array([5, 7, 9])